version: 2.1
jobs:
  build:
    docker:
      -image: node:11.10.1

    working_directory: ~/repo/frontend

    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test