version: 2.0
jobs:
  build:
    steps:
      - checkout
      - run: docker build -t hmatwiejczyk/next-test -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run hmatwiejczyk/next-test yarn test

workflows:
    build:
      jobs:
        - build