version: 2.1
jobs:
  build:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout # check out the code in the project directory
      - run: docker build -t hmatwiejczyk/next-test -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run hmatwiejczyk/next-test yarn test